
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bowovrvroxlbzgyvirum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvd292cnZyb3hsYnpneXZpcnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMjQ0NDIsImV4cCI6MjA1NDkwMDQ0Mn0.Xu5Mjjhpnwpx5aQow3hwN9ThkM9_pn8l36BwgjpMRM4";

// Enable detailed debug logs in development
const options = {
  auth: {
    autoRefreshToken: true,
    persistSession: true
  },
  // Enable debug logs in development
  global: {
    headers: {
      'x-client-info': `@supabase/supabase-js/2.x`
    }
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, options);

// Default error handler
export const handleSupabaseError = (error: any) => {
  console.error("Supabase Error:", error);
  
  if (error?.message) {
    return error.message;
  }
  
  if (error?.error_description) {
    return error.error_description;
  }
  
  return "Error en la comunicación con el servidor";
};
