// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bowovrvroxlbzgyvirum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvd292cnZyb3hsYnpneXZpcnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMjQ0NDIsImV4cCI6MjA1NDkwMDQ0Mn0.Xu5Mjjhpnwpx5aQow3hwN9ThkM9_pn8l36BwgjpMRM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);